FROM nvcr.io/nvidia/nemo:25.02.01

RUN apt-get update && apt-get install -y socat netcat-openbsd && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip --no-cache-dir install nemo_run[skypilot]

CMD ["bash"]
