---
apiVersion: v1
kind: Pod
metadata:
  name: nemo-vllm
spec:
  containers:
  - name: nemo-vllm
    image: tutum/dnsutils
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
