---
apiVersion: v1
kind: Pod
metadata:
  name: nemo-vllm
spec:
  containers:
  - name: nemo-vllm
    image: imokuri123/nemo-vllm:v0.0.7
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /root/.cache/huggingface/hub
        name: nemo-models-volume
      - mountPath: /checkpoints
        name: nemo-checkpoints-volume
      - mountPath: /code
        name: nemo-code-volume
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2
        memory: 16Gi
        nvidia.com/gpu: 4
  restartPolicy: Always
  volumes:
    - name: nemo-models-volume
      persistentVolumeClaim:
        claimName: nemo-models-pvc
    - name: nemo-checkpoints-volume
      persistentVolumeClaim:
        claimName: nemo-checkpoints-pvc
    - name: nemo-code-volume
      persistentVolumeClaim:
        claimName: nemo-code-pvc
