---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nemo-models-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: edf

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nemo-checkpoints-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: edf

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nemo-code-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: edf
