kubernetes:
  pod_config:
    spec:
      containers:
        - env:
            - name: MY_ENV_VAR
              value: my-value
          volumeMounts:
            - mountPath: /checkpoints
              name: nemo-volume
      volumes:
        - name: nemo-volume
          persistentVolumeClaim:
            claimName: nemo-pvc
