kubernetes:
  pod_config:
    spec:
      containers:
        - env:
            - name: MY_ENV_VAR
              value: "hello world"
          volumeMounts:
            - mountPath: /root/.cache/huggingface/hub
              name: nemo-models-volume
            - mountPath: /checkpoints
              name: nemo-checkpoints-volume
      volumes:
        - name: nemo-models-volume
          persistentVolumeClaim:
            claimName: nemo-models-pvc
        - name: nemo-checkpoints-volume
          persistentVolumeClaim:
            claimName: nemo-checkpoints-pvc
